---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 1m0s
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    logs:
      general:
        level: DEBUG
      access:
        enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - "--ping"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--metrics=false"
      - "--serverstransport.insecureskipverify=true"
    metrics:
      prometheus:
        enabled: true
        entryPoint: metrics
    ports:
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.20.40.40
        externalTrafficPolicy: Local
