# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:ooAThX5Tmuk+p0LpYc4YPXwTrXgL4MbEQT8LW1lHnqD3Ob+2,iv:F/wsFFBsbn3j/TKm9yfNbSUa+hU8Fvjz6jATkXsfHh8=,tag:l+z79JmJqlKMTejVZW9iUQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:uBwjrj1VfP+XphW+5kXxYfvnCvZVWM+WgY64ahyvmZf12YEQR6pwu05aa9GM5f7G1ykuavDvgAbIn9S4adsGCm6x8ACXB2HGt5RfmUUaZXTwdJBM6iFlVNRyYlUVsAyog1kCC0ZsIUS/P16nKo6Hh6g+H1bt+hIIUHvLBBTzMQCRvoS3MdigS4gpBAdDH4bkHKVCfu5kpNAfKUMuLfeGWTKdJ/M4AAkC2ek/Vm5x0A==,iv:gJCTY+XHeQJxJO22Kqg6YYqaSRQIA9DfwrHveY8AFRI=,tag:WBc5TNSKrN4aS4aOKyeQhA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1avfa4enawnghy3afp5ltzzwxv92fldr3zu2dtm2z3p4hvn2eaquq6lvlsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZVRxWWxBd0R4c3U2RFdj
        bkRQa3ZzdmYveTV6MkJ5cXduZ2RpdzNadlFnCi9xckJzQ2ppQ1VtMjBKVzZXd1hG
        QlphdzBpV2hlT1FMTSsvclFtSGtGNmcKLS0tIEVwb0UwSjYwS29GRC9WSWZzSTE0
        SmorTE1mR2JGS0xYYkpYNk9Nb1JGbVkK3a/GzvuHWxiEWfBQnhLS42Ldc5h58t1x
        YjJb6EaeTWgUN4RFS10Spi36W7eGvx8pBgIvNDfyUb5YZBaG6NWkRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T18:19:14Z"
  mac: ENC[AES256_GCM,data:dwfr5etrW297CQHJDNbWSA2SpyNoVdG0EYPjPrdt+EhEjxsI+CUBA/AIqDrlE03sseiYRUbHYYUGATQdGRhlJqmKXfaJeRBUAsSiyND0W5HuymHAX8Nf3szAHrNPNgCFpjllk9US0b9A52nZ+qI80zWAckIyV8s+XwaBKTMaAk4=,iv:f5gAJgTEMAJ3dKdVe93oYiNDIgF1kOGsCznWVApeP3U=,tag:M6Vrk3eeFsgDG4Hi/0ScFw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
