# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:XttYw/4wu9yFPDgj7rbmzBoSu2hJRj5JzugDTDNiJZr7V3U7,iv:GaYpwnj+zZFWMQwdZa5nJMcqQjgpWfskhiZmR+IL3NQ=,tag:3ERlyuro36BxZ0/Hs4zKAw==,type:str]
  credentials.json: ENC[AES256_GCM,data:Bvzu+E25xk9F0f6M3M5AH5Mz6mnbwN6Gv5jCtJiNK0JZ8BciK/mrDhRrY41/z2hKFzah39a9maOA5cQD4Isiq/ieD2gCJfGC9fLXt4R+4IHGHRR9Azce3mlwmL1ACzURF+GQ1YtXCU+P5YTmAWh8Q39J72HIRxyqSoZJi5+HxPkwXceE4jSWBPpiYTgXlEturLB19HPhjunZuecUX+v4I+I2msgA4vKPuO/i/GUDmQ==,iv:6FqfaX/vYMCkGE3aBdXIflmqXIdZE4tH580Yk3FyiMI=,tag:16f1iPWl5J9t5jZ9bzye1w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1yc2r0dnmtyg7cw8z6rmjh2gfss54d0u5g0zrz85ez2yrnhfg8fgqnmajc0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac3c4TDZ0RitFMHRwa0tB
        a0tGdzNlQndEbGtaRzk4bi83R2M3TGQrOFhVCnF4V01jR2ZGVXE0VDBVUVd1azU5
        TnVmeUZpOHVzVDN5VyszNERJOGRKaGMKLS0tIE13aE1pY3NBZlVuWW1tM2tXeXB3
        N3RoUXdOS2p0NEs5YklNYVN6a1BxOG8KuOOPnOQa/eqdl6dhkxlPmFcAVeFOom1F
        seewtA6hpWG3R4EkpEegWKaKqWVp4vbW1dULAH1TgcIuLUX07QFnsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-23T17:35:57Z"
  mac: ENC[AES256_GCM,data:PrIxUDxvNQXjgcXXCoElAbo8dW7jTc2VtiQr9bU0fzVZ7SzfUrbsM+QKkKbuG2E1L1EvCSzyBR/cztNzcoA9s0R6jG1GfFEL7EG6Apau/7aCwo2i5Tfs9CwKhYflj3yo7zHrabZFemeyXg1nA4qO9H3ce5684gkfjU6I3L+fTpM=,iv:WK8s9dtZqI8V+I7ZdzWi7KygbjGAgNhC1o6DE+6QRtY=,tag:uQGpiPMu1Fog2VxkBd7VUA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
