# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:HeirIxeS0fWO8iHRWjQV3bqvmJeCumDhuO0IP5oCbSJQM9ZS,iv:pw4AmZRsYm1UoimAY/8AQgUrFazQJJL2wsVACqf3Bgg=,tag:pEHOWs3pR1GFYvlFVJWrCQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:4eYsRH11PPTrM/GhVrQAbDy/RRdyo3zgAf5cgB2t5SLnQRkNvXXxbSdoj8kuSFsP2InXKl15tpckJGJ4zJmXFjgmb2jjh54srDR30i9eKoEjllHKvrbjRc2Bw94m4eSq6iFSUXlE7qMICPHT+bfqyjhUJTZBjfIceWav0pdgDM6i4GM9I6qJXGZkeaE/9rD2pF756nn3RSsixIuZsO/LVnBja14DWqjLVOKSO67diw==,iv:uE18xYHPBz88O1GZuICfoezBmjaIOtK1VUM7ZAKCXbM=,tag:nYcqer0qMnllqhbTNXHkuw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1avfa4enawnghy3afp5ltzzwxv92fldr3zu2dtm2z3p4hvn2eaquq6lvlsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcTU4SU1ISHJVa3FjUG5V
        QXgvVy9ZVGUvMnJjVGtGMzZJd0NNRklCNlZjCkdFajJSTHVUamZWKzlONG5hazE4
        a1pvY0tmUU5XUXFtcnplTEc4VXpBVGsKLS0tIHhGMzM3c01PamZMdi9TZmxyU2Fi
        YjJXelNIRWk1MHk1bjgyZVh5ZXN0SXcK2mu/aTnhmDRvyfPZDVcJSHTTe8nKeCwu
        wrFCoMcZLiA5u+GeLy/kxuKbb+c9Y9cSHAM4DbZBE2wzxWgEqU9Q4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T21:39:25Z"
  mac: ENC[AES256_GCM,data:fElSqPiURowuYElvY+ikJzXSNBO1UyxWD1dXiKO2OQAQ9Tlqtbz7LSaixfsSSN6AjImhe5YQfTkw/DXHSMF/Zng6U7rT+YyF+YoDWQPb/8rkhLx7QDjpODpyZIKUyDzZ2g7p+Utk5+xilmKKHgzKT2mrdiHJ4Tlj0gARI6pxLKc=,iv:ThgoauP6v8kZ0nEJDsZWZebx1EPLcsxp5G9lAQkZv2o=,tag:6rjJxWl0F1davffVPPkDZQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
