---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/terraform"

env:
  KUBECONFIG: "~/.kube/config"

includes:
  terraform: .taskfiles/terraform.yml