# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:cPg6ghQSxZb94BKlVAoL/eHXLiOuPOHCbsDQ59iNupQ=,iv:gAQDXvfKl6IywMm+1SGLVoH6dzyPiQWkdXyxUpzrudg=,tag:lvEGK37dYprNxFbkSEdnjw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1yc2r0dnmtyg7cw8z6rmjh2gfss54d0u5g0zrz85ez2yrnhfg8fgqnmajc0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMmJaQnpVdUZYZ1Mra2pp
        cm9qY3g0SG91ckQ4VGZ6ZW9Jb2g3UWNYR0FBCmFFREVyMlpYaVQ4RWkvYmxXL3oz
        TTYrS3lXMTNkQmFtaUpLZ2xQNGFFTXMKLS0tIFVla1V4aVRDc0V5Wk1oRG9PTnBJ
        WHlRUU80Ynp4bTZGTjYzQ09ObitXTlEKtfL9vf8wBsfJG3Jq74lT4ro8TcLtDGNF
        HYdA3YlfdzdMpGll5STo9v593FhNnJNrtJJTD3j0aSSxuj/rZ3iI/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-23T17:35:57Z"
  mac: ENC[AES256_GCM,data:eljb3pWtRX6/2YmMLu25BOQ/+g28PrwIf6bodAzKOWmJE/bSXV2B4iy5nTir1yJp67+FFVzNAF1cqW0O87tt/PcK79qFYqut78HraYdzIv0VPWFkhp+FbpGCdWksCc/2wZ/4M2o/+VXAi+ogtDO3j+Hz3OLeQ78Ybj0WneBryQE=,iv:WnwkFng1kgww8c6UNJ0LS0KWH1swPhGkb6z5nSIWHrE=,tag:JQpmNhwpUshYc54WaKAk/g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
