# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZW5ruqIvUXsXYsFgcDogfVKtCPMEG9tJzRz1TMhRWYLmMxWtOjSZYw==,iv:fHXmvIZit9sdYzySwdSKpRN3YZlfQC2iAvLAbVouYFg=,tag:FOHo1wpw/Z8PqP7dli2YlQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1yc2r0dnmtyg7cw8z6rmjh2gfss54d0u5g0zrz85ez2yrnhfg8fgqnmajc0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QndMeVdOamVtdXFqWldi
        MHF6eU8vbzlUbmhWWU54U2pPNHlCS050SVRzCndmMW4yM3hQMWNReXgwazZFQjYz
        K3lkVEFrclF2ZEVRUFlPeTl3Y1hNOU0KLS0tIExtNkZDR3FSeXhPUjFLZGhFWWps
        eG5HZ1g0R2JkbGJBSGtKazJIcWdXWDQK2x9nIY0uNnRVAtY8Xp5BM+np0gNO5I+1
        DmDDYeHqL0DH/VdtFvXffWOdU+KD7+7+GNkYb7sy3tVRnwYHdBOI5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-23T17:35:57Z"
  mac: ENC[AES256_GCM,data:1APzVRZAEd8yjAQGJmJw20FJnt3DKBM97fPqTX1n80Ys/bUD8AkKLHxqYgcj252zYQ7W517kHv2pJhmqIZpZDu2+YBa3XAWb3cP0zg3UPTiT/acyVrP/W1KorBmpuPNQOcowkINFncEWlVmPGUv7VN9d0vvPYb489aF2BBhQLaw=,iv:lFVBK9VbiHGBy8f1TcSbpQKw89pLtem9AcR1Amg1myI=,tag:EdlR93qD/tL+g3JAOU29RA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
