# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:FQOSVNGa+rL3o0O5ouG/NtOXVLjhhZ8aCOCfQfoROXzHUgd96y7KTw==,iv:j0Zipl1dby4E5f1Zs2Jmz7CYPIP+sfAJXzZMgXYwsZQ=,tag:1i8/y3IKzJIIMMXgP7hFWA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1avfa4enawnghy3afp5ltzzwxv92fldr3zu2dtm2z3p4hvn2eaquq6lvlsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlYzOEpKUHlvYjczdlhW
        NXFsY2ZHMDhNTlFyeEQ4NG8rUTJzc3Z0cHdJCmtrZkFsQ01QSHFHcStoQkVvcVFM
        TlRETkR3b3JuZlZCM0tuVWUrQjlrVlkKLS0tIFBvUmhRdDRyOEVNbzVwam1DWlVk
        ZVN5VHZZMGlMcXROV3ZuSEZwTE11dHcKw07atUG5+9ZrvsErOPoVh+atYaVnLYn7
        7wlJuxq72LijVWdPkVaDbcIXdbP/c3mAuG2tTHy165JQ8C/o/iqqhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T21:39:25Z"
  mac: ENC[AES256_GCM,data:WsniBa/TtMPTtjLlM3KKnZ5QGeOOeX3/Py31z3wSSfUTj9SDy4QLZbNQEZOlkQttUTeIijAnvPcWc4hXaFcMYAjSFRI+Nzab9wml2a3HwfP7uoyu9cU7FRbQ85ZYstQmoWV2jx48/HykmBZ7nZBfz4qd7cK9TveYCEWPA1qLKzs=,iv:dU7mkMuwMSkJ0SdrwtOyEA8ztWvhJQrLiIyRgipxXZY=,tag:uSkqA+Vipjj7rRtknHfecg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
