# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:oe+hSzpwqTKjUs3IMf+A7iZQeY5let7KWpWYxl3BhRtGMcvgwJkNpw==,iv:Z0b7FYUS4SKJrwq93zk4957HYamAoxnr9ifdr6eTDp0=,tag:SeTv2ug8QGBF3jMWl4uXlw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1avfa4enawnghy3afp5ltzzwxv92fldr3zu2dtm2z3p4hvn2eaquq6lvlsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbXVJeEFYei9mRktvZVJQ
        U2pNcmJxSDZxZDJDYSs1MUZWVkJFZS9JV1hFClRVVzB5V1BNSFIrdEloNzZtQ0l4
        UmNBYThwUU9JQ3FzaHd3VnlPdEJSMmMKLS0tIEwzNnVnOEZsdkZiSG1ETjNMK1VE
        OGVLS1dSa1pKWmdXdkhJSzdmQmw2WDgKWlsbxxNg8k/+GBDcwujdfNyv/4I++oUR
        hAMaAWne3Ew7wV1vZm7ZTR2U3dFLAfZbkvCzzFPvk+P672Y28asC7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T18:19:14Z"
  mac: ENC[AES256_GCM,data:YblfQrEMO2o7igK4ohtj9sohe6cndkRdts69tzz/dEzhb+Sc19K4A2IKa/kTnEKOKRwEsEN9Nuu7ufvjgMT4ceFvGide3dAdJKhTiamIgeH7qXpURmWGxVzuLHMX8AZAPliaqWkaekF1s0a/fynRkkUx631RuHihx96ZxBbUtg4=,iv:jl6X6W1og0YumrzzB776sWNO68vYKQimAHJRljcL6vA=,tag:X56Cfcxt5Xy4nMQCsI/FVQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
