apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:owart2H7naXDYFkoxUtbLhcx,iv:8DOpYdcH0MbpSNLAvhquhNaH9fer0YqwzvZOm9hX7G0=,tag:QP7vdgdKqcqgNQGoVe+wNw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:zn0lIDCbL27DaVBiR4KYqOyvlRX/HVQbQB+4ypmq4Jv6cQ7vFA==,iv:HsJ7EX0voOOiIRVIOEMi6WZeobRwx5NMNDTN+jNk0nQ=,tag:polH8K6hshSMkfGQXrbf2Q==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:xhtL6DKa3WUwzZBArnOSygo+hy4s3BSn6pJIpWhHtqk=,iv:uryHdEZhJcUHeIFdV8UxgS5N+l8br4Ra2omSc3abkYE=,tag:gg2gSRcaBVnaKxPLV28MjA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:RlLG+w==,iv:p/nT4sfzTLOqzd7vK48g9IgTADEe9lkdK7zo/iy6RlU=,tag:c6DVA2sr430iDJHTkcelvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVFNCQ2p1SGdnVEZ4S053
            c1dQMVNrdHppenpnbkRFSVc1OUs1Tno1a3hZCng3cmYrUmJXNTRQRVkrREcxN2pC
            UWw5T1ozRS9Cay9sbnAwSjFmTHB6d3cKLS0tIE1HcVlxTExhbDZFZXdFMjNzVVVB
            TzRDSzFySFhCaHJmMjMreUx5K2dIdlUK/VME5qN6UiwOJoYBKbBL8SGl0hGtXRZ9
            J6W5wqU3EtPc+SWSKKVXn/Gr3+Xh3XAQfP7tQ7GzeGeSLNivVd5xbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T18:54:42Z"
    mac: ENC[AES256_GCM,data:MAGpXz9JDQ/vj7aF0JNxu7eAzuDW2KXMK6GIkRkDE9HepgqV9yU9Z7xEQu2SuhVNXrHAlQOOe+V4t1Q7RwPJmcdH7pKHeqcCl1jU/1PrVQ/PtVAwCQZNPS4619jQBZ3ORemjiDUuul2ixj/PQ9On16Ha88av3KpRK2cb22IpKWQ=,iv:1uuXs3jBQz1FcmfoowtKjwaJmIlYb6j4f5DC7PBQrz8=,tag:B6VcWidT/vHta8S7TRJO9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
