apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2vuPKLVZJbI6QIrZVVvu+2B6,iv:CtD1iGlA7vgU18PgJ3hJSgv1rCdiHTUz2h62tdGT5Tk=,tag:LiqPKxiCkbj5g+59MG5shQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:gLp4TXfvXhGfkkXnG2xtLy3ZNERhZjyz2/yhKifqwjegSQtrQg==,iv:eHDkgepUqZCRkH26KU24nEXOyF16R4fI5Cnbh6xMM4Y=,tag:FuyzEaU0HZntuLEpXXIrug==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:RTlnwzOw4VROKtiAcYXvvP3VtIHEn2CT92R/RbQFN74=,iv:no/jrJAO880ODOJblh7xLO9UiaUD/QMtEosvsu37yxg=,tag:erO7WhB384xmsIsTZ4yRtw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Qz1CjQ==,iv:Ck+dfyzptF6zDeCg0VaMMmJTIvGvh/jaGchZyNu37G0=,tag:wLGIBgKhssHudTxwtvikVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM2NkMUFpZ3FuQWMrV2lE
            NWNQTkFMQU5NTUhYbHI1SmpRRG9JcW4vZHpnCjB0d3NsWU12V2d3M2JTOHh4azlv
            TzhVQWE2a0x6NjJQRTN4RUE2aDR2cWMKLS0tIHB4aDhVQjk0WUhTRENHQkFEOHda
            Qy9NL3VLNTFsNHFXT01wZUpYZ3p0dWMKGyvQ/LKM0OH4aGBglv6YfDBK58O9hcu8
            mMeKxenwdISHFBEPxtWUHi/XxUS47RyoqMMnZtVucWvb3whxM3ZhSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T17:38:52Z"
    mac: ENC[AES256_GCM,data:vlYxDOOasT6KB22geqT2YRoZCFtx7boAtgtkdOwlUF171zbNrceNCFEknBTpaZYTo/rKbPjqScJJTtTotWewz1Zd4GhQXDDSsRX6gqxpKPvBnEGUr+cRzJnUwFRvxNiJkU/9yMt2W5yrB+yvqKkzbwubRadL4E2tYt3qvio5cJg=,iv:LYJXd5SLwIOKG2ox2MyebRaInZtDgvlctJM7nC3wj9g=,tag:macIKy7KQp5E0KBxveADqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
