---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    hajimari:
      title: Services
      darkTheme: blackboard
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      defaultAppIcon: mdi:application
      namespaceSelector:
        matchNames:
          - default
          - monitoring
      customApps:
        - name: AdGuard
          url: "http://adguard.${SECRET_DOMAIN}"
          icon: mdi:block-helper
        - name: vCenter
          url: "https://vcenter.${SECRET_DOMAIN}"
          icon: mdi:state-machine
        - name: ESXi
          url: "https://esxi.${SECRET_DOMAIN}"
          icon: mdi:state-machine
        - name: Unifi
          url: "https://unifi.${SECRET_DOMAIN}"
          icon: mdi:dns
        - name: TrueNas
          url: "https://truenas.${SECRET_DOMAIN}"
          icon: mdi:nas
      globalBookmarks:
        - group: Dev
          bookmarks:
            - name: GitHub
              url: "https://github.com"
              icon: mdi:github
            - name: GitLab
              url: "https://gitlab.com"
              icon: mdi:gitlab
            - name: Cloudflare
              icon: mdi:clouds
              url: "https://dash.cloudflare.com"
        - group: Cloud
          bookmarks:
            - name: Gmail
              icon: mdi:gmail
              url: "https://gmail.com"
            - name: Google Drive
              icon: mdi:google-drive
              url: "https://drive.google.com"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
