apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:+3iUb3Yfg+X1qE8RuUN6b3n127klx2+nOF3eqrc9giShJn7R,iv:ais2aHH5vB1LaNz4hWpFrswzhiu8HGU9UxFhCNZHQLI=,tag:0AaeRvL/kW08qaNeh8rFWQ==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:FF307Ptw2OrAZ9tPm6VV0ztTv7PdGeTivCZ7nBxSxaTlXiTOu0pZ1tcRIsGOJVB07JovKt9rRH2YIDHuqBaBd6FFxZlPeiq3QwxAfr+geppL5Cygfl1wr+pghaeJFVi6E4gdTLAfkoeZteIL4IMG+SELKyT+CU9h+g0mlX92z/FVYYvHdReT6It6a0cS+xpoqVOlg5Xokd88fJAOse7+u1uQ7EhuOAbQpvGVKy7ZHQEbF4qmjBrHoQ==,iv:yaZ5Fd03jLkOm5zrydwa7y12Y16V5iNbA086JWjRViA=,tag:soumyWVvSTNaJ1/p8eiGZA==,type:str]
    credentials.json: ENC[AES256_GCM,data:1Pr6gMW2BgWNEOgKXt/Ox0G9Xz7fhwmglCereRL+IUK4fIsMvDgn47a3QIkyQG9kIqbNug+6c4iybmYXPwqeePpTYFc/SUvpyOyio/6b97/uyQv9c59SsHO7yJmmb9ggvEbz,iv:rfS5K35uHyMWg53XC6D0D2SAM5hCFvVdaxUBwQDB0mY=,tag:wQ0YjHMOrrvdpJMU8YbLuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUDAvd0loRlY5Ky92dFZY
            RWx2ZlZ3aW14TGRoelQ0SlNjcjJDanU3M1VJCkx2RWtXWVJZOW1URitYT0lQbEY0
            SG5mR3UzanNhUmNOOTRtZ2YrRHZxVTQKLS0tIFRoWnB3TjI2Yys1b0JMUHV0cmxj
            Z01ZbENxK2VZM3ZVOC9GMUJxd0sydVUKnNFUXEGlfXJBHMjlmv5MBr8RzW2tDQ3D
            UkD9176XkKTESxeUch+1ut7BrtPdQVgguewA1TPbxLmzLLcq/1jdUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T18:21:32Z"
    mac: ENC[AES256_GCM,data:fnIqZ4zuKdrvAsdQmMYq+fPJ+AGFeAS6SqT/lncMadDhGV7/crq+0neODVqQRy9jsT7hbRECTV41yX69pbghOejwCViTLF6teq0wRFHWg1Pv79Br4wV7RsNPJzWR3Pz1hoXHWMwqiqAyAKRDRXUMPB9mLf6H5toYHHKCa+r+3/s=,iv:FzlbqtjQahmzQ8AvHgaydYv4hclIa9tRQVU4TeMtM1w=,tag:kfPgH7d4FE/E/oWwhXlIGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
