apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:dFb3v1s2q4JAWGeZFziXmVze7fVvk/etuCYeQSsa7c7GNQ1n,iv:X8PJ8lRJ3he4P0TpNsQlq278iA+uIpKkncNXYPHDbxI=,tag:iu0h6rE48L1OZ1gjgnso1A==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:H7dWirEQnNz8tmigMti5xutxbnDeDRsA0vjQ+Hi41uAB4TqlgqOq98ghejivGdQEc4ikAayIM8in6rVj5ZUX8ZTxlGO/ep4l+/QY9sl6kNZWfjqLJSZJKB56QFMTgA5mtPFOd4wIEjEFEUoI43f7qZFD7TFk2q6VKT2zesnoxew8u5iyjzKZCobW3wglTvyet6WN0y9gPqv1Nn0IYid3XBPXEzPoO9m5CP+A5dUpOWhKMOYGdnnp0A==,iv:UoSYUoGIxuSYugFIEsYjM6gIEa6vlRK8yd+LxSQ4w54=,tag:dse7x9ImoxnBIDzUk6Zgog==,type:str]
    credentials.json: ENC[AES256_GCM,data:hzl6i5YRxkMUNlnu0Pq8T3AZn7T4eziUhGhqhthiSF3B7pBoBYuzMr1ydvopgVajuMBoQEPXjWkkuZpZjCvWHMlT/7heg9+MtPSfKTaUs7KSQtm3AVhTtSmD+ilaBK8XrWqf,iv:0LYPZ0FuwaDSvon0SKXQTOw2U5DS9XEHmpwgtLpj3uM=,tag:k2x66kwcXWu+1vlH+Yn+PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETnhKbUUzRGpZeXFFUXB5
            YWFvZnk1Vzl3ZDR6R1lXaVM4TTcrN3dRemlzCnBOcFJVbnptNzVJd0lHbWRvd014
            U0xJUGtteEV5Vnl4aGF6UEQxYjlTVzgKLS0tIGtCZG94aW1jalVlTWU4MXRwRmd6
            SXBMMEpFNEJPUGMwKzlFZWVLZWtpeXcKSYXUp7wdquXqbjKdM4kET6fO7W+9j/tV
            actwlJflZcCh746gwffTCVja44SUD2ihanzqlR9hYZ9ByBnJZyAyzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T20:09:38Z"
    mac: ENC[AES256_GCM,data:rTrNutvUSdnv1F3oS7umpplELmhnNZo6hXp4S9mjGqMcawQSFiCsYPC8v9PB/DABmAFeOVzEOBKkthjMLnWkBZbT0tXTfAukgFyvllEfb+QhTfrbIiUmD//nn6JvoyyZNGzmYfplGlu4AXIgUmOmMAW6QLYBsS+AW5SI3CV1AuM=,iv:xl5AdFePzCoYyrzCgZj/JK57vj3Ml0/JJXrOvzZDqMw=,tag:qzqIqglSptzUbSjybckJQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
