apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:7dHUNWDNsnZDowxKcYwjJ1ePQ0Jl3NFYhpXP69KxOLuNQwB7,iv:+z0qsYz8hIsSBMwAOLwxmwwGvvJc8BGOZP/u3r/fUvQ=,tag:kRZevx3bJWzElZMQgFt9UA==,type:str]
    credentials.json: ENC[AES256_GCM,data:n3j6NrN3rBkamqmTB4DH5fOMJnpo8Qu2G4EXH3PWreQJU8pus05gmAiTTEh8GZyb8p5sdTN1LhV4Rvij4PW+2p2KEUBrf8XWWJd2MrUq34I3bCdonmC60/ukvwajxhYRAHnRjqH513tPZ5wDEjVnJDPWzFVh3nLNEkZ44UAN0OuHH/nb/hNaCbcfM+KDp80dY5yW0EQuHFlRwtlV7B+RHdbzgNYwwiL94I4wn+tydw==,iv:XyZL4bxRga2/RxPaSkFmIMhemIq3BgsYo2KszAdcRG0=,tag:SKpQG+Ije5jCk0Cif4seoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tpsr79vtdxhvrkdexe5fphjs334jxp3k76tn2fjgs2f4mdf0c3sqgw7wr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK3NEdzBXMW9uZ1MwTjhO
            cUY2SERIcU9ZaG5VRXFYSm01b3FhNWhZQjJzCnczcUExRHVwaGpLd0s0VkF4Z3Mr
            Mk1lNW1tTjJmUFJHd3k4YTVqYTllc00KLS0tIGE3ZUxCdmpnajVqd0NSekU3WkZs
            UkR4VVZRRXAyaHc2RWxhWHB2Z3JXcXMKO/yP5IX4ZTqI5/lJmS58tw7gYUiR5d5r
            75I5Vq1pSKi1gnnQh6DmdaKbwd12RPIa+GmY7gy4yGpRLhOUlZiVzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T16:41:18Z"
    mac: ENC[AES256_GCM,data:BQyC5JoZo9Rjb10DSWZcJSRRIMQgCuAKeO21M6r8PHhO/A7N9GWaq80NNzYcd2bEdszAxjk1j8dk39IEW1sx+jdxnU+U2/wLKEWbLT2TWtBUaprPYCSomCC3W2lYfxEH9NK8HH5rnWCgv+17GJWuRT71R6Qo9hE3QNC8gKePCKU=,iv:BOD9nnvmBLDf6loQ6HTx5UsIUxdhCy+riUPBFJhWR4I=,tag:8KHmbYSSQVY9eqp7uMbXRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
