# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:jRaDi/0xaoifKR7JSLyliiVOxZQa8ZatPoLEV67/PXNTZjuKo2YX0ROaQt4UAsKrOIwqb//MeXvwxspfDYlEZgqvh1k3RPQIQeJiLJl9EuEN2niW9gQ5i5StCViNlQivpNXD/5uVx07KsEgMGh/FMgwZRAsdrkbj1OCC,iv:zK0lYaxMeJewJpp0DjjcFG3B9/LB9fFclKCyBHaA4nw=,tag:IF7/U9+WQGuCUytnEaeA0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR1MvTnQ3ZDBOYkcrYTR0
            SjQrZDUvbC91Q3d3Y2RpaW02alh5bHhBaFU0Ck5wM2w2WTl1VE1Mdm1pa2RJUHc5
            dS9MU1FIcWtmRDRqTHp5UVhaODJhZkEKLS0tIGpESy9CMHJ2SVRVZnVxaXFGZkcr
            U3UzNlM1cWdIaUJQaXhhTXVPZXhkdzgKArTqtMdBSybBMRncctuB1igbJSlThw1M
            5JDasDlPaoLgbO42qvcrKNIYWVLXHwVHgmdVulJt+06zVTAODIaHZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T18:40:49Z"
    mac: ENC[AES256_GCM,data:FKmx8SQEdtX7hTVubO00WaKpMoP4np+OwbCbqFde+ADmO0re1cOFY8/1bbARiTlr76otov8cdxgvY6ndKKSV9XTtEP0JPmzrwKZf1F6v1vekw2eY8KRecfyz3+Im2W+Y5VYIUmtfV3LobP4Wr5pU1Gl7m+arzu/d6f7sP6z+b4A=,iv:cyhPaaRBsoZUW369wOjYjtzWHfIAdCSc/5e9hPCjKgs=,tag:L4Ce8XkyVo311m6QtDSglA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
