apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:BrZo1Do=,iv:FvV0g5pnfivbo7IDEGZsaRW8/A0O6GLRTSsN51EeebA=,tag:hGGAinfTXXYAqBmjS7gdwQ==,type:str]
    admin-password: ENC[AES256_GCM,data:dOWRq+ZhE3d4TwTwmGVv2MEO8DojduVl,iv:LTlboZRqOUfsQYVcgzVxL2ywsh50i+fltfLtVSm550k=,tag:6+kFaFuee55D4vLG5C8qvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgw6u3x92lz54nnsfkjwke8r2wkunxc3s9hdr2kn8apcxctpzfeqfakdup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSVl1c3VZbjV4dTJ4L1dw
            NnNPSTIreUJTSzVpQy9jOHVnNHNOa1lDcVNZCjBHeUNXZEFybU4vd1JzQmpRaGJU
            Q1NiNXAvMmQwQWN3bjhqYWc4U0JOVHMKLS0tIHZTTmNJUzVKTzVGVDZVWFZnY2ll
            ZWN4dGQwOFZndGM5OE92M3g3cWhMS2cKWjjJ06QCdcPVKlB6NmrBSC123n6votPb
            NB3mQ5CQY3UlLcV3+wlRz576ccllk9sUJkum/kBOSkB6AMJ7L3+rFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T20:53:22Z"
    mac: ENC[AES256_GCM,data:Gxpzz8DYU+Tx7uszDO3yiF7YS0uildldDu6+T4QTqn/W069mR0qIM0pLvdtbYRRYhtGCV7y5ea9kUr8r5NioXxIhphMTAyQLfaQUsoipNz+Ue43bSRAu/NwYz6sm51r/jwPikrRIMvs6gr3wrGPfqIv1VHHSJOVI3KVqdZdPJyU=,iv:Xw/ToAh7+mf1UZrX2s3ZA+kO5Wru9VUc6EaiUDUgnFU=,tag:xdSE0ehTn53STdmtVOIbjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
