apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jdospxeWBHrX8Pj12pxBG/R9wbGtt/p9,iv:90i4fYAqiGB6OQkBPMWoPSQSpUQyA1wuVWqjblAlmgs=,tag:WKaOsNwkrOLvTF+WoaxRCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgw6u3x92lz54nnsfkjwke8r2wkunxc3s9hdr2kn8apcxctpzfeqfakdup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y21uMEhkSDgzVHk5anN0
            ZW4xTXRySTVUVHBHS0lQVXJwTWNNcFJFTFU0ClFUR0hsNDFxYnU3ZEYxUXFNK0ZM
            cmt3bXhpOWEyKzc1ajZhR2hTOXVIekUKLS0tIFZnN3NvSTI0cGFIZFFEN1Z2Vnd1
            c2tGSm1xaXZuSkdaZWpSci9Kak9oQ28K7xb5o0hM5dNyBHTewSwxY09ay6zQr0YL
            0qpINUEpcxrB71e96G1r02debxrqt+6CTgkisnLCGBmXRiklPzElmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T20:53:22Z"
    mac: ENC[AES256_GCM,data:sho0jKweJzXkzYIANd7LGU/tDkctCcxLY0wQk/M2Ubf0+ueGRfqh6vSJ6p1YMoNm+4BLIz8YPLQ63Z3cPRWYaeDU6yFpVJMolTAEIv+nzGshnmUl05misKGQvL5J3xm0x8IeZmijg69sfcgKMArnm9T9mXa02xXk4vg0MuPlSwQ=,iv:R63ZT2V2psqrDuOJIYGbyU26me8SnDf7ncuYOTt9w44=,tag:GuZuCqrvYCS4qblcblAqbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
