---
kubernetes:
  children:
    controllers:
      hosts:
        "k3s-0":
          ansible_user: "pi"
          ansible_host: "10.20.40.20"
        "k3s-1":
          ansible_user: "pi"
          ansible_host: "10.20.40.21"
        "k3s-2":
          ansible_user: "pi"
          ansible_host: "10.20.40.22"
    workers:
      hosts:
        "k3s-3":
          ansible_user: "pi"
          ansible_host: "10.20.40.23"
        "deb-k3s-02":
          ansible_user: "tom"
          ansible_host: "10.20.40.16"
