---
kubernetes:
  children:
    master:
      hosts:
        k3s-0:
          ansible_host: 10.20.40.20
        k3s-1:
          ansible_host: 10.20.40.21
        k3s-2:
          ansible_host: 10.20.40.22
    worker:
      hosts:
        k3s-3:
          ansible_host: 10.20.40.23
