# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Yo5fpcp2OqGZCBneAkxrX7Qi,iv:yFJ5XgS8x82THg7ikl33f+OXyTaUbOWBxz9tRHKACo0=,tag:oiww5cpiMVPeL22NUdwvwg==,type:str]
    api-key: ENC[AES256_GCM,data:2zBpr948a/gBIG63O4fxKe3aMI2QrjWziM8WSa3SF7WrA79F8g==,iv:UVA8zASutCOkVfyv0CkYP5DbCtk2NuJ5RJLMeTvQ9/s=,tag:FccjNmwVx1FAi0KpzKANjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja1hlV1hBWWJaeFpOZ2Zm
            SDVaWmRMNEhKcVQ0RkhnZ1ZTS3JjdHlHWWo0Cm1yK2J5di9BVlhhSnBEbW9KN2Yv
            dXcyQ0tjL1dKR0Zici9QTjVtK2NkK1kKLS0tIDZUeVAzZ3NsdEtIYUcxdmY5czJH
            S1kwZkFLek9weVVob00vY3ZWbEV0WVEKi1aRSI0hOMVknl/Spb0EjN55zEyK6/PX
            a9j5Crf7GeMB8XVidy76Yjzp+xp1Lkq6d3RXBpbUX8Hz645WOmYGBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T18:52:27Z"
    mac: ENC[AES256_GCM,data:Vn/LG8tmPFP93v6gQl23q6+IIZmUTCPnrF/mQNc4fPlROddlw09wI9w1N/V6mn6LCdLs1OFtdAKjutGFgEwYZO3xrbkuuzqs9zqtCJ3vmpjk1F+NXu/gtViW6Nx8SILuvJ2+xbqLovqvA+XzfVX/nh6bkwPwQnv4uHkQlvRDAQ4=,iv:whXwvkRtcu/5h3GilDo4beOmgT21ukLY0r0JwT/+KF4=,tag:5iarKTlEOgowX73iJDVBjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
