# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3TAEn0yTcEZCL8HXZAK4megM6Sy/jWx54fW0xqdXF5QW7BqPSF91PA==,iv:Uwaqwfn3OCG4QwMKD2s5VsOqW7yoXbvdC09edppz1dc=,tag:AqMP9sqzZZnHCTw4EHLs3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUExpVHlWc0l1ci9reVky
            YVhCa2NTTzR0TWZVY3JUWndTZkIrQUREVUR3CllJZG5RNnBhckl3L29XYTFyT082
            NlVqeElYN3NQeXBWcm5DMEdhQTZPK00KLS0tIEw4UkFhNm1YQ3hsRXpBZ1BWSXRt
            R09ZV0QrNEtOcVVWTjM2V3k5MWRMdjgKoOgS2nR557+HqMaLyFiCEXNrJtduMjvY
            wv5oMnjG9H3hwOTxtfhnxGQlPScrZS80JPK+7z7lBXEn9oSS2q8zyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T19:06:22Z"
    mac: ENC[AES256_GCM,data:nNoxIPJoBaDLdpEN4Z56qy1a9FEEFQ/vxkIbsV621ggRBucgGr8IqW7tQBNlJHtPcXQLgl/zWWDNEZImmaRd5OjOYOG+xFKgypagZiXYZcgYn70vgDn2Tz7gYChOoK2DjBKxTVQloJ2oxdrWq0jGxuPfIcRHxF0n+nhfuisxCZM=,iv:u3hVDYCDKxGf9lPBx1SwTc5CM+Y7wWMz+7y4JO1FvyU=,tag:4y4EpAlbjbOSGSy32D0Ulw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
