apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:rSbOLD7g4RgGrZ8b2g3Ow7DcZk2O6YutvWTt2Y0q7kLAr3GpTP3K5Q==,iv:lzG2u0jpMOaJHvIl4iriLj4NA6clcydCn/k2TfzDE4M=,tag:xqLds9IhnrmT+kEc7Hmkdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgw6u3x92lz54nnsfkjwke8r2wkunxc3s9hdr2kn8apcxctpzfeqfakdup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM1NDb0ZFV3Q3THNHd2FG
            UHdtTUFIWHhvaTEvNDlqeldTWHVSb0VxOUNrCmg0Zmd5bE80RXl6MkwyRm51a1lI
            bklpZEV2Q2ZUekxoT0xNV2JaUFh1ekUKLS0tIEY0cGU1M1BMTjFsQmt2ZmRLQzMw
            WkVDUEFPY2xNT00xTzZpRVRzMWpBVUEKrZ6UyT7cYhnYtiG/hZGnkcnDxmlUD9ae
            GunefWay7240kYI6p0UayiezE9e4fwfd3EuI06Kv1mj4mjUfRORBDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T22:42:04Z"
    mac: ENC[AES256_GCM,data:zoPujlCz6U52w6yGqiLtcWv13rDOvXzoxAFJVtRSh9wEEWJPJ58+nTYQqsPTwRsqtU+XrkP4kVYVczUCCU2pXsIdF5RzsxK1c+MZVn1WUctY29FJBMd/y3oKmHeaE7zdVrd+E8poOZAeUxQBy0890H8whY01/bwdst7SjWhf9eg=,iv:5+O+a4ms6fxzDjfbaj2drPWApESYRzCmr9n/AFJZhTw=,tag:39IdnkyijSFKaUpG9n2FFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
