apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:A9N2oI05vqZQlaeoVNiWAeEbH+PumnUwk4UuT/iJQxIVbgdsP5sOQA==,iv:NvqvPSpXCfzUh150UGFO/m+uabi8DqHkt1lvWfJYQ1I=,tag:lQYqMRUeY2wTxO31cE9rsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgw6u3x92lz54nnsfkjwke8r2wkunxc3s9hdr2kn8apcxctpzfeqfakdup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dWRpMGJQY21YSW9iTDZV
            K2VoWEV4L1BSTWt4dzN6dHhGOU9ERXRvUTNnClRzb2R6K1ZJY25MMXRYYmpwYXRF
            S2Zid0R6QTdaYXY2U0dQY3NhcThxdFkKLS0tIEpxWVhzUUxqblFrODl1RzNEWFRv
            Qkk1d0xPbVFBclZDbnpGdEtXUHQ5Q0kKMtzKxWuAtdg1tvmWpEc6mYZm9DFR3Lc7
            WgAAV31LUiwgSHrUxNpwSd/OpvR1q1QTPo9psglN8kQjagvL2bcvFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T20:53:22Z"
    mac: ENC[AES256_GCM,data:r8g7Ke43mu33nKAZzabh8mzWKTDVdiEyVJ/ryEQdKcNh6Je6570GxpKyMV0CkIj9pGVwJitoXfcKl4oUcwXbL5KY47B0X8pdj0aIyVhj1jlzgfP27X6fw8D9Rb6qNU8Yy5Uudrhakv0493jVJmfCKVfBTtkEn+SOZz5/GIX67d8=,iv:d8Ew3UAHulNRroucMqktjIh6snwGc6bJ5ecPkNOcHVI=,tag:e+W1bFMO0HQEE71KYfyuVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
