apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Xc0qDy8elMw83LYr+fu18nAsEE25vg/BgvhSDEN6x1xQrvOixrikRA==,iv:q6EEqa1Y24PKft+BsZzpe4Pi+uRD6INy19gLMcIf8+8=,tag:E4jjcdHmoUGYS6j7Xd6n0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZzdpQmFvYWRwQ0JUTFZD
            L1Y2N2I0Q1p1eVlDSHpURU04RGM3TE5UelgwCjBnN2lpSkJPTmwxcUZ5RWUzU3hY
            cm5UN2phNFNkYXRoMEJ1WjVxdTBsSEEKLS0tIFEwd0paQllJd0phR3ZJR0M0dXVo
            R09ybG9vQkc1MC9sUVR0ZWVsSzNHT2cKlGiV9jr9SH9gvdEuGiVvI9VHcV7I/I/Q
            YsScC/SZfGq8hiklALNFh2BphUoZUbW3kB1taq7OF467yVcHCyWeNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T23:21:33Z"
    mac: ENC[AES256_GCM,data:xZvh74J7Jv9cPVOHotRRQgImEp41LDQpjiREGkaIZ06gMp6t0oqZYf5Ug0x0fdlvxC2ZVR4TlOXTfOMbrMUJXRnHZsoVKlHG2cVhTzlQ9Pi8e/vnzwWtUgfBfe8xa/k8kqlQYiM6Gz/SMEnombNEJYpgukeo5rIaaIlwI3EJXvg=,iv:LsBWCkMcDgdJ1OwA1qH6kOp4t5aJowiWrzIz7E95rbc=,tag:r2HNqAZrdtEnuEYlg2rJ7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
