apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ii5G1lQKO2J/8C0lcqaL4vMOx90OkPrgrAj0Kq7efOPgLosngB6eUA==,iv:wEg9qUEyGqxbJ0nYR8m1B87GywKijas0qY6zf7/jFjE=,tag:CQElOBIDf5wmfQjl7ofgJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgw6u3x92lz54nnsfkjwke8r2wkunxc3s9hdr2kn8apcxctpzfeqfakdup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR01SZ3Nwdzhjbld2R2p1
            N0dSS0llN2t0WTdXblpaNjhzczhkYWNjeHgwCjM1YzBnZXFraVd6YmxCbHQ2L3dq
            M1g2cTdkeFgwdWZJWUdjaGJjZ0hMTEEKLS0tIHZ5NEVSZHhpcjlyek90bTlUQXNQ
            c3c3VzlSNzlMdGNzK3BXR2JpSW9IZ28KS8dtjuIkKPUZAGLhv7snjRUXZ40qt1ac
            f2Ea2o0eF1XflGyodrlHmsktZO1qN25Z3KZeRWG/W50qqoS6WDTAbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T20:53:22Z"
    mac: ENC[AES256_GCM,data:UJm74PQVVzi0mAOJbWR0iRTqsu0RMZImRaN+FkgEKy4KzVxpQKD5IqFESGMat4TBO21BW0hNct+IfiSWwM+dX5+TzUYPM8h7ejcX7Ybw7SS+Uf/WPI2kvCLFKoAexMtFST7P/c6jGWsy18INutPuO07cvNosKKYCKsRWZTec+Ns=,iv:PDjIiM6KOntoWcKh44hHiHBz8OfRIXwlzdCe5ozkFdE=,tag:vMd0wqm3GYLEU/MkavZe2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
