apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:6A9P0dt1yg51iZD8gpyM,iv:E3YReDEOlKaQ4ovsyMgm8taVa19siS3W827r2YmNxYw=,tag:Ga/wR4vSXsCTbx5Vmjb+Bw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kZbun0CtjeFGZSQNkmoS73uj,iv:pygwD8hTS4dqw+VH1lSu/nxBXuZeqOCOkztj/j6pAfE=,tag:c01lomVPG1KnW9HsBLSLpQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:/IeJAr9GWKLX8qaPVG2nthFT,iv:RAespqoMDL+6vZfYL25qgll5Ax4Uz2CISdB3k0weUj4=,tag:EEgm7UeBu44Qa98teXUEBw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:VlZOMO0/VkIK3GpZTl0eICV5n27zg0WRGVNH7gU=,iv:QbvdDnnQUZglkRH1tqYOclibHOZ3P/qRJarj7Oykqcg=,tag:DO3YFnPWJreyxc+l6xjsxA==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:RgypoEYKxf6mOKDsoHXifOEOavdXiiaUQEobPxKoFo0VRyZacivpoHJOvMFaIViLrFY0inCqibzpqgen/Z7KCVBQ8Q8mKA1zfUiCdJCkzn/cY+wha/B/CjoPr/gjhyvatYSIxeyqhFra2NLmvDBeah4NQmpo/7fndWoY,iv:zPhyolTj3M8+bwyG+PE7uYTOVLXRhrUPGOVs+JnhkFg=,tag:EbwUiePXMkHRYaG9RfJIRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdjhlUGR4WGpaRktZdHNq
            T1F2cDhQYTRtK25PamdqOG1sTm1VOHRvekFBCmJZK1VXakNwNWxkeWVjQmJodFh6
            cUpBQ2M5VEd3aW5NL1FmQTRoNWZvMm8KLS0tIDNYeSt2WnpGOHdoazFqT3dacGlY
            ZTBjSi9mNFpveHk1Q3BFNnBBcjVmanMKtF6gSHYDo121rXDvIEys/VdhnGveor57
            cbu72m+hUXp9Ef6BKpEjZ8KMM1KTOV3JBAIlxjJZm+EuEVhX/XmLHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T14:29:12Z"
    mac: ENC[AES256_GCM,data:71CBz5BS8YZUsVtkis2VZS4ANewdSWx/2F+NwTvF7AYXCrLV17/r6/ymzG/PsGzGb5i/BzGbZA8jlvXlPB1f8kJROLv6UWmQCT6RTwOUbOHbu3NLoFTGLnp13gVCNrXXPrmChZhGiX56wXR0KCkWAmQYfWYe3vkT7/mfnPBasC0=,iv:DAuRLA0FJu5wYvV7o3tFvp3bxan1cO5Cl82VIU44vgk=,tag:1BhllDELNKc285wsh1+Gbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
