apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DkrUm4Yh3h4THd0ALTQi,iv:30pzMRrR1sQxBEJB4/CKkISbNKUTxpvi8OIrF4utaDQ=,tag:tRmENWuwDwyu9Ecy0wlXBQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:bJiKJSim6hPLYGQvTabN1yAK,iv:4oNTrfjw4wd8kFTzWmbxHgI/ldHCMj7gQSpm4wj4RE0=,tag:gejuxDFnzCjBcJCC5JDM4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFK01Way8rQWg5R2RMWG1u
            VmVIYnpKSVp0VlhFZ0hiSm1mSk1meDM2b1JrCkpXSXpuNXVZbzA3YnZpMS9HT0Uz
            N3B3cUtjWGhPZzBlVFdlQzRDTFRYVVEKLS0tIHVvVlg5elZTb2s2QUNwKzZSelJx
            RStpd3JEVWJTSlIvL09LMjY4UUtadXcK3uJQxPH0zF7uLcEOO037coNbYh6F6oR4
            MJpJ/JTpbaPzxSsw/VzU6tYGcOQXByp+UhyV1+KDfR9RnRBi0knCMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T00:21:52Z"
    mac: ENC[AES256_GCM,data:/PAdFEe7S1pcVGuD30skEluN5v8W5OyQrQzmMKkRFRxa8nsTmvLcY3LH6At28V8WzvDAhqki0YXRWUTFmkqRzP9vJKRlFgkw8x1tBhdmLKLB5L3+24tixGmJfSFdkez67GJY9ftsEUrUOyAQC0m+Y4OeAv9NosxozvqKXm8hI0g=,iv:7IOEQpUyI1wynSq+jriWfCTSvB1fsk5bGi7kxs2zTJA=,tag:b39UuTD3804pMSvaFh3Ldw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
