apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yzmE5MlVgWk3/eljkDL1,iv:r0gzyYKIENJ3aDNPdIoZe4rQ7NQYAU8fuRBFHpr50OQ=,tag:93otd61CitGb0oeB2Kq1Hg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GT2ZeKqn3TpzFRYgGkFy1JQ4,iv:9Q7JtoXJj7yvHlZgOw9PNSb1+jFSuK2zrXvBVqu+zgA=,tag:tprvfZh58BWXg9R2nlCx1A==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:bG870qkOELUXba7Ge171CjHM,iv:Xa1s6yq4MNG2+uHW50m4YhaDEB3N8BvUSRJQT0FeR+U=,tag:UmJqoc6cj5wKjKLX209QNg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:vEcKpq0DKmDh5hcC7qXrf4gif2rA4WoRaEOKj5I=,iv:eH3lFE/hlAcoDiZgYkq/6GprZavcKx6HQD2j3ljI6Bo=,tag:im2w8DBGDFraOh01hJSmbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld2w3cUJkVExETkNZQ2dh
            WXdqYjRORC9PelhJYjFiZnhMWGRRSFNRQ0ZFCitEc0JreFJ5TmE4ZkoxbkNTZVM0
            a2Q1WkpaUUZOOWczVDg5T1lMVno2cFkKLS0tIGdHR0pFWUxGRVVRSmwwNDIzdjFQ
            YVZpQUVpS2wvRS8vRzFkZUcvVlcxTFEKp8dithcYT+W+QthdR1TK67Jr6iulb01n
            SfgDLOeRS7HDqpBMJSa65DIpgYoDcLYzDGF0xkRbYFHgvZKiYKq54w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T00:34:27Z"
    mac: ENC[AES256_GCM,data:pdH8spbhxJ1CnA2CN3QJCE3oxeXsvOs2BtcrOMpGVMD57s1xhdu70hhcbqoYla6prxyDO8cXJh1sIAeneJW8o4phRhov++LRcaLlJwSY9/pe9tco0i2OjF5qCHkG1lwz6SpgozszUL8i63Z0E1UD1x9J5FpyWp50a+Geyh9xrxM=,iv:BPILWND5+gkqaDxC5lufo2YOly0TDh+kA0pvOjSO0p4=,tag:+PZ7zXlj8o+o6P50+gS4yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
