---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 20Gi
