# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: homebox
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    HBOX_MODE: ENC[AES256_GCM,data:4mzCV9G6qPn/Iw==,iv:K/Qk12/zYhUUySRlS1vrltnuBa0AxBy1nOJ+MTfsCRE=,tag:E4XR2t7tOvAVZzKa+dGAGA==,type:str]
    HBOX_OPTIONS_ALLOW_REGISTRATION: ENC[AES256_GCM,data:0oMbAg==,iv:fWBqfQybr8iI2QmblQSPJ9C6EdNGtj3PObmSZzTmF0I=,tag:uo8vjhWXxFPkwU6kC1muvg==,type:str]
    #ENC[AES256_GCM,data:KtyayTc6PfnJfhzFLriQF20=,iv:wbGqsQyNECmZ62MwFndLuvxNyWkMBmHJdB2QeQJqJVc=,tag:lLYZaRbbfU0F3ATOq57oWg==,type:comment]
    #ENC[AES256_GCM,data:pWMVZVPFElzhttqsoUeZnjIgiiITn580Fg8=,iv:wi9J9LgJ+KIy9OOHm3qRcNgnRd9KrHFvwQ6FwPq25pw=,tag:FBsYyfsxZaHBQgKBKrEkOQ==,type:comment]
    #ENC[AES256_GCM,data:H7gncbVPhCOj8X9x7RgM/wdRwAWUsir3li4=,iv:QoxQMYqa6QbK+1gcSjuOTlEce8FAeF51/MpGsK/T2iw=,tag:OLsbXNa6kOaEwg+LmVpLtg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tpsr79vtdxhvrkdexe5fphjs334jxp3k76tn2fjgs2f4mdf0c3sqgw7wr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUWF0N2tzV1RIbkRaYUVN
            VjRlT3JraEQvRkZ4UlFTNnpNbnNzQjF2M0V3CmdlWjV6L1VSNmIxRm9UUngxU1R4
            UC9JaEJOaDFQM0lqTXYrNkJCWVJLL2sKLS0tIDVNejJxTmp5akI4REpZdms2R1NU
            akN6TjFvd2xRLy9uNVdGaklUN2tUVU0K9hNQZUHHX33CIKWFutvQgjR0D8qDhtpR
            +5Pg8D9chji44VXrHzZpE19u+mV2YYo2oERnpNfopeWEuvkJ/ENyVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T22:33:28Z"
    mac: ENC[AES256_GCM,data:A4kBvuiVUSq2cS0rKc6bWEp1oAMRHU7Fa4bj1P9FMUv1g64nVd5wl0MfLFL5dvA3PgweWJcdNovnivPUzH4zlAGDMgvgTHWg0yl0+rGy9U7wOIzvCkmaUT8Y3aH6HmKYFnzaPR6Q9NdIKWMbtjs+W314tnksRnxT97+wfxj+PzA=,iv:Lh7ALRQ+iDXJ+W6vK07GHy1X9G0dwm7h55E+bD4Po9U=,tag:zaUgKH7fkVay6LxuhOgjsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
