# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./it-tools/ks.yaml
  - ./homer/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./hoarder/ks.yaml
  - ./searxng/ks.yaml
