apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:riOfvEKx2TnW7Bio1lxa,iv:i9O3fNEUylRefU7/HpyHYXgWTL3fIUYsXaKIXZ5crOc=,tag:I90zKdc/kfpgKSCoY7uumA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:oAqJIUfWGqLCivZAXdxnfCPOd8dG,iv:yV5kTY+jzHzMClEcl2guO5x4j5wAs4sTspOnjsVQ/Ow=,tag:ybuzeZKYZ0rnQGcRzbp62w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:fdNEfdui5e54pXtbfhob5BDdeS2Lf1HgUebutfRg7PfgRnYe,iv:01liuD2CJebIstgCS7OTukR69lfo3FpPzfvbEa28zf4=,tag:SIN2yHqywtjJX7eeenDqXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tpsr79vtdxhvrkdexe5fphjs334jxp3k76tn2fjgs2f4mdf0c3sqgw7wr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS2ppV2JEQVREYXo4a29l
            U1JVUUpQWFNGM0tGN2R2bU1JSFJEWldNbEI0Ckhlb1F4MGtRSlA2clFWd3BsbnlP
            d0FnclVYVk5aUEYrNFAzV3lmcUtVVG8KLS0tIHdZMkdGQ3VKZnFXODJxamdJZGpF
            UWNiaTlwV00zc1lFeGpxdk5OT1dwcUUK/uc2tJLkJgm7X2bdpXcvuXO/biRD2U9F
            avRCyygQMQVe9Cw8zlLBwVhNGMinHgBOlspNtiWE69LLn/5YVCMPkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T16:41:18Z"
    mac: ENC[AES256_GCM,data:I4/SVrpX25ZRAZTFD15hEKwWjUQbl28JpbTpiNlBoKN0ZzoD1HmgpkDXXUnbYp2M9X4UtIq7cgk27UpiluS0o792J8qKlfCeyXq3s9esbfnZw4iAxJJgpL7SQ7mtKeAnLWHTmkdXy7LRi6synmvU92YOCoX5BcngAfQXS1pgXHU=,iv:qyZiKELIkbBrb+LZ7E+1Blg3RxCTaQQ6iaky/EmBOAo=,tag:ImcuTlGDElKRpIDMp5Ko2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
