apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...
    SECRET_DOMAIN: harrier.network
    SECRET_ACME_EMAIL: tom@withersoft.co.uk
    SECRET_CLOUDFLARE_TUNNEL_ID: 645ff453-db7d-4853-88f1-9742b8f64a75
