apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:peQrirzYC6zl3CAmCD2hEJ9JyZUXXIo1utX56n4g4AeEHy/SKykxem6jQ4XSoFVStMatix17BQ60Z3ad78TUcUhq099pZCg4eoRZOb6x65IUZWc5G/H+T/ZbdPI27g==,iv:NcT8nh/OFn483aJzDow1Lm2PzR50TXCN0pUvhKzbGSY=,tag:/dhfuP7rCRn2OqUenKNWrA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:2giIXrMsrm+LAHy+DXy2,iv:SwMvZJEQ/lIwV4K9wBcTD7fnkjcVd1BHuzhlT+0NuAU=,tag:liDtJtelNPZDqj/xYwFCnA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9biweXAXJWhqL1AVJI5SJ7xwKSA=,iv:t0ztbtcoGdrQXtGdQuiz8Y1AwBzM3Vs5L6236ASdvUg=,tag:Z8roGGfhgUywPIfae9tnlw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NihPGduftfjM69h+G8jW8kU3H/+7/7g1PoKUMIQuKRpJ1tpQ,iv:D2AgEQN6pm9v7iLe+iPZDqukZ/H/2BE96Aw6QTnY1bc=,tag:DmS64mngx3XjzZ1zRdq25g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTmxGU2NHQ2J3bkZSOVlt
            TGVhVmE1V3h3aWo1ZXNEVWFzSkdXWStrV21ZCkpUZS8zbldaRFZsVkhZd3ZQcUR4
            RkYvTHEvdm9HeU9mRVRNbUhOamJnT3cKLS0tIHcrNlZmcGllRFZHSStzeEl2WTZl
            dzJOa0YvM1BBeDZOU0xXQUlXVTZEN2sKCKwOzrD/ZXSolZ/NeEcsU4DbZ0wYg5YC
            kEnelLDkurvwvMw1ij0uN2TMowLH2E0ZsL1Im1DZ80X5A8pXBpdAJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T18:21:32Z"
    mac: ENC[AES256_GCM,data:TO9dA+W3V0dyUMr8NTknQ/pF6zwVGhb8IPmGgRWy/mg1tQNjvBqU+QQWHL7BqRArDoHXk3+f1+uefsA7eu0/VJCftCfEdfjLOojtgg7+D6i3ZmEIdV6/uBIyJDVEfuqH97zueDc+ihv+DoLqzG6E7ipGo+qQIda0LJIBAt/2Xjs=,iv:ExNDllHDCWNoJpff6eBEkCeIKYYC8pqHTloglegdQoQ=,tag:qpQ4jX575h1MNSMICp8bkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
