apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+tf83Fo8D215rWzyTIm5,iv:GopcuEeQ/PZA8NtqKJ+W6LczF+1Xow3qcj02OFMVhpo=,tag:9gJ27uzQKsrXSimVENG+7w==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Ki8LysRt4sV8Avk+rYTonJZTFHNaSBupuTqiHia2GRrSYgYV,iv:QmREw3aiD2/cwUqh/BDUoGH6V0AdBr6lXApe8UYkMm4=,tag:O1nAbuQGgFaIaOTAiTKHcQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1avfa4enawnghy3afp5ltzzwxv92fldr3zu2dtm2z3p4hvn2eaquq6lvlsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5KzR5ZWNoTVZzUDZCeS9K
        Vk5VMG5laGgxR2llVGZLVWgwL0dzS0VlU0Z3CkV5ekp6TWsvRU9ZYk9VWjFvR05E
        SDhXRFNhajEwaE1SOGxVTFVzbWtUY1EKLS0tIFVMV25ucmNKWC9zSE82TEo3Yzk4
        OUdoWWVobnBoajUwWlVzWk5sdnFTSk0K1UlIDLswAZeLJvB++PAEXrDc0RWR56CJ
        qsJYj09P0SFuhnhGMSVeX9krfav58KfDHCQc5vWMLTIHN5oMU4lA7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T21:39:25Z"
  mac: ENC[AES256_GCM,data:4SDZLE+TpGabqRnHka85r0UHYx5/Z+/0a0UrIAGfInKeDBmoib/n7rHHAIXPu1P60JvZonjAolgYGav5kFFL0heTwH0CMeP3txFs86yZcgrBt/74El27ZPCv06MyL1G37UaYXtKm68W41HgRm/LICm/ZNohW3LMabqry/TP2/dM=,iv:MoefOlDTWLWu7koRZ/pvbpFUOeol0WeUZNcXzZu/HCs=,tag:oxjEfYKo1keAZQVQjN91gg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
