apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ksAWeAxz3ITwLQws4acm,iv:CGtpQjA9O8bavRduizj2Y2PsDOyN+44PtN3IcOdEcv0=,tag:zvGc+KlCXhHJMHAwsx36VA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6By5n9Vtah8E++DrF+IGPemeZhO9+xmZNWXiNK4CTzTE86ts,iv:9uopfU+vKinW+fHs5fDv46B7U4gKl+La8irWUkWQIMc=,tag:J5kw+wsY0FxDTpFyb8gJBA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1avfa4enawnghy3afp5ltzzwxv92fldr3zu2dtm2z3p4hvn2eaquq6lvlsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aDluUmx5S1loVytxUU1E
        dnM2UFFOOFBvZjlYaEMvMEhHREVKcFlBNWt3CmJNVjlhUGpHZVRhdVVSbW5heXlX
        UEE5KzhZaEEzaFMyNFQ3VHMrcDR5cDgKLS0tIFZkeUh5ZHd2N29uU3lyVlRQTGJW
        Y1ZxYnRCSWhDOERnU0xZWktKTUZwVXcKMUCVCjYiRY9p3+pWtsulJPHZres/5y7x
        ExTmwfdb206z7lY/3uXvcI2WfkWDfrUobv++afSU6bB6iEBnrPiYuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T18:19:14Z"
  mac: ENC[AES256_GCM,data:dm7C28Y8+h4SBqNp9ehMxqohNJG5w0eeb2HcdnHosVVboHhUeWa+fbt8qMFhLhFB3dA+dqgQZGrHIdpiCmHMyUSi+9u5GNAWLp83FVudvPAcVKRkcAl89W2ZhsaHtCkKdjWkhmlSfZCNccc/LteXViEDJOAwyA7rfYLbcynp/Mc=,iv:t4/HjOqfUMP+N/ls+BaOLu/PIiFoilY8pg2021YJSMs=,tag:Mt7LmTicqfa7taUTP7KcYA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
