apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:mA7dgpUPSm0LFStKNWipeXGe5ZnFys1uFbCKaTqFdRKQv39W1jLrMn5uMBU6H2uSRARmqeMEDg07hs34hOe5FGqNICcI2HgapR8M,iv:28Ff4qM4p2puhCBqClEMUEnkKPvwPi/Dc0+loyotutc=,tag:2ASyjfkB41n7UoKfP2BQ6w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1avfa4enawnghy3afp5ltzzwxv92fldr3zu2dtm2z3p4hvn2eaquq6lvlsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQVdTYmhuUXlyeGZiVFE0
        NXU5VlVPdW5UaHhLdWNWVldrQ1lpOUtsbkEwCjVlVGhuSFF5RDNVajZJVm9YWmdH
        K285NDUwdHFYTm9WalpnanpaRjllbkUKLS0tIGVmU1BTVGRhVzFMUEl2S1Q2bmJj
        bUVsejJCMVp4VEtkczNKL1pPbW80dWMKnRFI93Y5hSuRNby0WUmFFgGyHdGyNqQq
        HyQMIM739JG+/ma1oRTB8SBUBPlhOwm6S1POesMu00B3LCu5rhddQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T18:19:14Z"
  mac: ENC[AES256_GCM,data:Tnr2YcorEWzXVjMGveq7xqCpj2v905fSAl5gDWMiIg7/7dLCn/ZI52CPTTHkJVisk8PQcowRkcxq6pCxFx5iU0U29epwBiNa04K0pCeNekyGwKeWFosDywUUY2q4o2SF2yeYchj0C2hF45iuRsgKZkEiEPvDKfaFgCz5aQted8M=,iv:qq7gnWfcARYqQpxtVdHyCujbzKeWA/Pt6savTWZvNV0=,tag:5TAvqLl4g7ZvDD0EguEuiA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
