apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:29nTDRsb8nzEn8nyscuFn1Bp4dAGM9xvh+QAxU2Geao=,iv:YzcmYKghlH15MDoduaUxc7y3ZQUG7ksysNSlA63lIbs=,tag:CUv4V+zBVr3VSBt/6qNqSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSUZ5NVFFZnVMVDgvbzBu
            RWpVcWNHbldrZlpUY0NseUtuL043dHRCbTFNClBSc1UvM3N4cDhXeWU0Y01lSWFv
            OGUxdTZiY2ZwQ3ZoeGZvTFhMSDdYYm8KLS0tIEI4WmFjTHJsM0dFRDNXRzZOUXpZ
            QXk4UkpLS1IxY0ZuMnRYNWNEOGlERVkKYofcEynT0ZvIwYpUDhKlWL/3NajNWMPi
            Joh/B59ed/irSK7bqj4fmO1ZIgEQVoeyDhD55brAamO/YiRe8ZoYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T20:09:38Z"
    mac: ENC[AES256_GCM,data:gL5mKr+vL7+S8NLojiUY3nCfQvW2YFoxW8ROfu6Sv+FFaUII5Z5n+dnQzOp6QZ1RqFylOytjCLCZ4ZuAOHWEMUDidqABi0KfTG6yyydc9uYOpfRi1WIX+o39CgSq0g166W5Ca8mwULPkaunwd5LiUabrS/oMI9YbTccfsingFzo=,iv:qlxUgwlztukeo0O3b3KrXhWdMDHfoQt7zxWn+YNzT5c=,tag:ZpntNN7S4qYwMSm9AJr28Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
