apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:NR9U5gz3X4Uf7joc0b7Dw0Hoyktl2Fvsjg9hBkQCRwU=,iv:nFc7v8kbAIdNDa91qdYNXBIlfdKF19q7fWe5llDWoZM=,tag:OrTV8sb06wHMujzgWJONJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tpsr79vtdxhvrkdexe5fphjs334jxp3k76tn2fjgs2f4mdf0c3sqgw7wr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ajZ4T1BTR3lJR1FqdkEz
            U2tRY0lIeCtBdXIwQWlNN0xyLzUwRklveW13CjEvVkQ5QWlrdUlmdng2MnJzVmRN
            RU8vZGM5V085a1FZZzQycDNQS0JkdmMKLS0tIFVoTnZ2TjdMa0kzMElydENCTmxx
            UXNTSmEzM2VnMEEwakRtZi9sbDl6bTAKo/916OCX8wlAURmELubp4gJ4GKs2bfYN
            OgCXWjhslFn/xIy2IMzDrQd7d8VZ8HbdElCtBS2hxbt0qFFH36y0Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T16:41:18Z"
    mac: ENC[AES256_GCM,data:fVBZwWeUUDcmd1E83S7VJUC0HlveI88mVMsQ/p1Sntp1aIx/3xbGY/Kf+EkZjI2idwMtozPwOyGtwHem8/LouoOVTZAJZp159lT8wC/ppEoYsdqa2V8XpIMPK26UcNemNdAh7zpYP8wstuZuWdasxgd17PJu9NV524PDLnIbOs8=,iv:3b4Kw6MCR3T7ArPeBSRJWd90B1IVKZiEHaVzOfns//c=,tag:gLxZBebGrsH2nfBsoQBUaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
