apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:EckYpQeAbz7au37GTSprQSCJ979f9CkHm9A1evYb1xw=,iv:v9NFm2vjGRQCUuHvmQwI016TnHVgcuSxAQttu4n+hEA=,tag:PYytuLoCZ2To0f2IoAkhNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ0x5OWZyajc1OU1SNTli
            Y2tKYXJPTXhPZEVHQzY3amRYSzdHaSt5QjFRCnhKRzlEMlRkdjZHNEJvNEFPTHNu
            YzZBL0t2d1dhdTNZdDBjeWVtelZpR00KLS0tIDl0SElJR2FWTVhKNW8yUkRrSWVp
            bDJuN29jaWwzSm51VlVrYnRBMjVXalkKpQYbdJqsBiwpukFlH2Klw5Ip9rSb9erh
            C8zM2ZXS9TtZySZXLK0fQl5V58j8m0TZ7PgUt9tM3vEyOY/GknvLgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T18:21:32Z"
    mac: ENC[AES256_GCM,data:rAim871tOrP24JYvfbx3tuNkI2OsT+dx2bMcQmiwYXc1jISk+p/9JB9wYCa0qR3lAC7qgg3fZDG075ZrMj0os8qooOYl/HYhs10emDs17aiiRDDN++GbjJ9bm7vWJxP9mV4tLttrIyFbmDor/ytkU6ZDol00fbvvi3xAMlruf/M=,iv:EIob65v4eduI/Gz9XkMPBXM/wbFbGpnMOv/157a3jiY=,tag:9ni3Zd/oofAXbN7oKWocWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
