apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Ivt3W7iwfeGxsoNnAUxf3aXsjqu5910VqN+pKhurWKGUa2T4Kg==,iv:r2auhFFSWjom1I/l7dkHI40mRvnQzvB/HbvRLG5FQcI=,tag:EMs2FzXx1IThjS0xUm9C9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSmdVL2hqbHVCVGUzSStz
            L3RhS1lWMkFmLzQ0cDlMZnZZM3h5VkFJZ3pjCnFEYkE1Zit3MTdXOWVqamJNalVm
            ZUJCeXFJMjlsQWJuamR4d29vc1VUUXcKLS0tIDJRai81Y0lGVVZ0aVFxbm9KcmxG
            MkN6c1NRQU5GMkdRV0EyYXlOaW1GeUEK8IZU12RN6P/2tKh53BVFC68+I2a6a2sR
            jaf2oE8N5s694LLSuXaMIf8nM5kB8JLTPBpQdiAde0QYy5y0CHN7tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T00:21:52Z"
    mac: ENC[AES256_GCM,data:spJMG4jPxCFVOVCaYNbjqBBpEADxI4nnvcOXtCAV9hvRXUgqics4cOSszx2vkPRBSO4p4oGtARKVFFAMd+7uPV3tvjCrzVbbAOoxf8lOb9w/UYl8TIzNiamAhHeBVvgY0SWFudGwft8b70fE0aVKA+PAOZ8wz1aIHSuW7H0vHK4=,iv:AnvC/elMEtamMRvKlYbBIGHev6zIrdiipdkJX6N5cg8=,tag:e/kb8/SstxI8pcP7UvdoFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
