apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:6joXUr8SeIwMxZtOEx9vdAufcwwphjDO2lH2hC5cLiNb41CPig==,iv:+KDzL7eXjAIXdRJrzz/nrPuWVBsX0GcPOd8fyf+JoxM=,tag:56LJxPNY9ToOFc0BlwhE8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n9rn8hp54r09fvr5e3em2rqgcwchu3hexekn2jetvh775unh4vqma4wpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYnJLS3l6cDdrd2Z0ZnhQ
            MmJuMXUrK0JWS1ZweStxRjUrcy9SVEFYRUZvCkhKVG5KMDF0UlErTDNJRGJuZWN2
            RU83SlVzbGVvQUQzODhoeGlyQnVjQjQKLS0tIDdpSXNFVEtYMjF6ZWdnYkllclJB
            N1hXWklIcnVPUXg3ZlAxc2luUTJxSmMKHoaD7d424K17z+gO152sKGqHtvwNaNDZ
            s71hTYYmiBKfJ67p+SOQl+IilWXCNZdDt68+Iszz67lamYMSgat5iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T18:56:38Z"
    mac: ENC[AES256_GCM,data:JiTtNNEowXLKjaGAiou3l87VrMePmqn86Uu+nfNBSDwf3dZwZjgDjWj9yAab1Desg37m8+MlQpNW4ugv/K+mzxIAPS7lkUUJsMlvmQOTXaj0QbAsCf5wc8KRjiu9Acx1ubx9sGAdED7VutBuhU+YTivA2S72VEBKNvOsjfZnZhs=,iv:QsmcSvMwMYXQUj3I5PAnu6oxZY/ADv3aGXDHkuHTSA8=,tag:jgoRVNjPiOt2PYrEBK+TTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
