apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:NXYMNWSePnf3yHuYDN2ypjXcAf17aVVa+Pi2rH7DRrs/c2Tz3JdA/Q==,iv:q8Bgx27rxnQ/v7z0xId3Pumsvd1rBPUDF57Cbbzg9zM=,tag:Kby07ITOhvf/CkGiAw277w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ29NcG8vUVpvckJYWklG
            OG5kS0JkYUx6ZEtPRlp4YXg0Q3RkS1dVbWh3CnZxZG15Uklyai96UEJ2LzJJUHpY
            UmlpVXpvMzhJdmRxU0JaeWVadFBiTWsKLS0tIFMzYzdKQUJRSDQyTHVHVWJVdHRX
            STFBaElnQnI1dUp5YnN1SGxlcGJkMXcKCh667/DYMhtUKhwYJ8y9wNoKiIm4M2NC
            tZc0tKTvjUI7wKDRvOcDHDlnYUIw4dU45h/5e+p1UnA9u9mVfjW7tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T18:21:32Z"
    mac: ENC[AES256_GCM,data:3bSngyd2VbPMVm+76R1mMlz+H/tlaJthsfmLQ5tCqLwEf6YUZMlR20A/fn1L8pi9LtD37yim1Hcg5C4ECpRDNJ1MzOO/y0Cs9Dh5WeAnaKLOkkVU2Kl9uOZJZN31HnToYPfUsqaQcY3rSxdayqrd2VaL4ovVsLga+uA7NlEKVj0=,iv:wjzThmk3J6MA4/kkyFzXAB8NQ852K55+Z3Ou1GNfqcY=,tag:px/4QSXa1mYCl1AvUXB8UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
