apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gEtWCNAuSyk8v2ed/LtlqF94/fBVUeOqYaa5upzxq85SS8WuWDBOHg==,iv:5jDPoxN/AT1ZYsezgoeq3Jk2xzgiKSvKzgSA3xVpino=,tag:NRLJiyh7MsT1U+Nvbk8p+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tpsr79vtdxhvrkdexe5fphjs334jxp3k76tn2fjgs2f4mdf0c3sqgw7wr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ2t1UmtNTTh6L1pvUXRU
            S2RpaFNyYnEvTCtJakVNWDNGZUpwb1lZNkdnCmRvamM0Um9qYU9QbFZyN1BCZ3V3
            eDZxSzJQdnE3ZElNMGNuLzYvWGcraGMKLS0tIFdrYldiQzZuR1FINE5pd2QwQUMy
            ZzJ6aklWQ01PTDdwejEzY2E5OVk2NlUKZ5ESzXO6I6bbWLWAUYblTHer12/7DcAx
            Xi4KnUvYR7jo/Z9i6I/bL6vVYrfpjzfWYr9xeeRA3koJtMwlZFblGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T16:41:18Z"
    mac: ENC[AES256_GCM,data:dm1fMytP+Aenm67PvuONNIvnjA+gekijoxvat98xxK/X1rUYuT1K6JCcyBjPzT+FOS5OuZlvEpi0qW0w26UYN9gDn+z+domC2KRcx10KDr4Qjw9toJFwU0E+Vq4tgFcsNjGzDKLQk/eJHMQV9cCP9XyqfGgM+6BK2osOin5WpBY=,iv:Yer9RksWEivVhnzs8JbPgZgQLxruxVisiU3ZN8qdgYY=,tag:/dK6BoczdjaonOIdZbnM7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
