apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:CgxNnTqB/3k7lrmWSiPv+fLQOdjLmoUOpWcWs+JRdQkmBhRI16FSng==,iv:supokuVfeHFWkUPo1byr3I/IeLcl8hZGMzJ8Uyhy8HM=,tag:8Lysc3Uv+cnCmmno89aDlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18048ppjndf86u2kze0w8mzl6rswzumug2uzqm8kxqvs2yytrj50sncjp7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQmRycGVDZGJWZXRJekNx
            TkVHem5FM2lDZmVwdzRiZmQreDBZWFhDaG5nCnIxVzIxeW5zMitrVFJJa0hFVTNt
            M2ZhVjcxZExJOS9RaEkzQVVNTzFocWMKLS0tIHZVUm0wL0ZKbloxS1RiblRMek5C
            QzZhM09ybE5uQ1ZLcHJObkFLWDUxL0UKpg5xOXVDJ93JI/PzR9Lvjg1dM5UqTZb9
            /5wKfhL4sL7s1LLGH4NdgiBlzw6SM+GWD2uVwIdF2fmFgzaUER8d7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T23:21:33Z"
    mac: ENC[AES256_GCM,data:Hc613JRik2s09cjl1mZTGkDfedd0ZUAeFGRKDPksFvJAWXLgqmHMnqAsg4U7Mv/UEUILWmHORXgvcaKK4YrP9sPGlA9XOWu9kN3kw88LUw9x7DQx1dsL7RB6VR1iM3dYUf5QjhApkU4Hz0zB6AHieJLq3jfXp+tseaaoLURks7k=,iv:Ogd3JsC17exzJdqMqLtxWCZo+Uam0fsQR/+hbJt/Ysg=,tag:veWwnOFtkFMC2v8zB84g6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
